### ISSUE TITLE
Cannot update challenge_protocol

### ISSUE THREAD

**Issue by tech-kio** [zopefoundation/Products.PluggableAuthService#63]
Hello,
I am trying to change the mapping for xml-rpc to map to http and it seems it doesn't work in :
/acl_users/challenge_protocol

Using Zope 4.1.3. It doesn't save changes after pressing update mapping.

Thank you!

**Comment by jugmac00** [comment]
I am not 100% sure whether I understand your problem.

I only setup **Products.PluggableAuthService** once, and then I have not touched it ever since.

I am not sure what "challenge_protocol" is... I installed the "challenge_chooser" - did you mean that?

My setup is `cookie_auth` for browser and `http(basic_auth)` for XML-RPC - this currently works, and I also changed them, saved them successfully, reversed them, saved them.. .and it all works.

I also run Zope 4.1.3.

What exactly happens when you hit the "Update Mapping" button? Does the page get reloaded? Maybe open the dev-console in your browser and make sure, that the reload happens and also that no errors show off in the console.

**Comment by tech-kio** [comment]
Yes, the page refreshes and there is nothing on console logs. I simply select http and press update mapping, but it doesn't keep the setting :

![zopeprob20200127](https://user-images.githubusercontent.com/47614426/73157634-a29eec00-40af-11ea-89cd-25c316cf3b04.jpg)

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2020-1-26 23:39 -0800:
> ...
>I am not sure what "challenge_protocol" is... I installed the "challenge_chooser" - did you mean that?

The "challenge_protocol" is the way, the challenge is implemented:
e.g. via HTTP Basic Authentication (browser login dialog)
or via an application login dialog (together with cookie authentication).

It is what the "challenge_chooser" selects.

**Comment by dataflake** [comment]
The fix is in version 2.3, which I just released.

**Comment by jugmac00** [comment]
So, obviously this was only a problem on Python 3, and I must have tried to reproduce the problem in my Python 2 dev setup.

**Comment by dataflake** [comment]
That is correct
