### ISSUE TITLE
Using new IPrincipalAddedToGroupEvent event

### ISSUE THREAD

**Issue by sgeulette** [zopefoundation/Products.PluggableAuthService#71]
Hi,

I have defined a subscriber for this event. 
I call some code that take into account groups users using "api.user.get_users(groupname=XXX)" on each group. 
But the new added user is not yet found at this moment.

Is it possible to notify added user later in code ? So a "api.user.get_users(groupname=XXX)" will work...

Kind regards

**Comment by dataflake** [comment]
I have changed the order of calls in https://github.com/zopefoundation/Products.PluggableAuthService/commit/b5d2b8feb196f8ac08425dcff989ae21bb8c8ae1 to clear the internal caches before sending the event. Can you test the current `master` code?

**Comment by sgeulette** [comment]
I had already test it but it doesn't work.

**Comment by dataflake** [comment]
I have done some manual testing using just the PluggableAuthService API itself and have found that the new user is found in the group. So it feels like this issue is not in PluggableAuthService.

I don't know those APIs are you mention ("api.user.xxx"). I am guessing this is a Plone thing? I don't use Plone so I can't help you there.

**Comment by sgeulette** [comment]
Thanks for your test. I will investigate further.

**Comment by dataflake** [comment]
Closing after 10 months of inactivity, this is most likely on the Plone side. Feel free to re-open if there is a problem in this package.
